### ISSUE TITLE
todo or to be done

### ISSUE THREAD

**Issue by micuat** [micuat/hydra-book#3]
- [x] add youtube videos
- [ ] more contents
- [x] host on other domain? (i dont like my name in there)
    - testing here https://hydra-book.glitch.me/ 
- [x] cover dynamic pattern
- [x] strange docsify issue specific to ubuntu+firefox https://github.com/micuat/hydra-book/issues/1
- [ ] what else

**Comment by micuat** [comment]
it's good
